[2024-12-28T17:03:59.634+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T17:03:23.747821+00:00 [queued]>
[2024-12-28T17:03:59.663+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T17:03:23.747821+00:00 [queued]>
[2024-12-28T17:03:59.665+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-28T17:03:59.718+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-12-28 17:03:23.747821+00:00
[2024-12-28T17:03:59.758+0000] {standard_task_runner.py:60} INFO - Started process 390 to run task
[2024-12-28T17:03:59.780+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'manual__2024-12-28T17:03:23.747821+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmpt3p2o6lz']
[2024-12-28T17:03:59.797+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask airbyte_check_sync
[2024-12-28T17:04:00.099+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T17:03:23.747821+00:00 [running]> on host a68ea757822e
[2024-12-28T17:04:00.677+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T17:03:23.747821+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T17:03:23.747821+00:00'
[2024-12-28T17:04:00.750+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T17:04:00.933+0000] {airbyte.py:104} INFO - Waiting for job 60 to complete.
[2024-12-28T17:05:03.277+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T17:05:04.471+0000] {airbyte.py:104} INFO - Waiting for job 60 to complete.
[2024-12-28T17:06:13.973+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T17:06:16.724+0000] {airbyte.py:104} INFO - Waiting for job 60 to complete.
[2024-12-28T17:07:22.575+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T17:10:23.483+0000] {http.py:199} ERROR - HTTP error: Internal Server Error
[2024-12-28T17:10:23.624+0000] {http.py:200} ERROR - {"message":"Internal Server Error: Error getting connection from data source HikariDataSource (HikariPool-1)","exceptionClassName":"org.jooq.exception.DataAccessException","exceptionStack":["org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-1)","\tat org.jooq_3.19.3.POSTGRES.debug(Unknown Source)","\tat org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90)","\tat org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:636)","\tat org.jooq.impl.AbstractQuery.connection(AbstractQuery.java:388)","\tat org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:308)","\tat org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)","\tat org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:875)","\tat io.airbyte.persistence.job.DefaultJobPersistence.getJobOptional(DefaultJobPersistence.java:870)","\tat io.airbyte.persistence.job.DefaultJobPersistence.getJob(DefaultJobPersistence.java:866)","\tat io.airbyte.persistence.job.DefaultJobPersistence.lambda$getJob$32(DefaultJobPersistence.java:862)","\tat io.airbyte.db.Database.query(Database.java:23)","\tat io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:31)","\tat io.airbyte.persistence.job.DefaultJobPersistence.getJob(DefaultJobPersistence.java:862)","\tat io.airbyte.commons.server.handlers.JobHistoryHandler.getJobInfo(JobHistoryHandler.java:359)","\tat io.airbyte.server.apis.JobsApiController.lambda$getJobInfo$6(JobsApiController.java:131)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28)","\tat io.airbyte.server.apis.JobsApiController.getJobInfo(JobsApiController.java:131)","\tat io.airbyte.server.apis.$JobsApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)","\tat io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)","\tat io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)","\tat io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465)","\tat io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)","\tat io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1583)","Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 155986ms (total=0, active=0, idle=0, waiting=0)","\tat com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686)","\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179)","\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)","\tat com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)","\tat org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)","\t... 26 more","Caused by: org.postgresql.util.PSQLException: This connection has been closed.","\tat org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:1009)","\tat org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1726)","\tat com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:562)","\tat com.zaxxer.hikari.pool.PoolBase.isConnectionDead(PoolBase.java:169)","\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:168)","\t... 29 more"],"rootCauseExceptionClassName":"java.lang.Class","rootCauseExceptionStack":["java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 155986ms (total=0, active=0, idle=0, waiting=0)","\tat com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686)","\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179)","\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)","\tat com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)","\tat org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)","\tat org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:636)","\tat org.jooq.impl.AbstractQuery.connection(AbstractQuery.java:388)","\tat org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:308)","\tat org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)","\tat org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:875)","\tat io.airbyte.persistence.job.DefaultJobPersistence.getJobOptional(DefaultJobPersistence.java:870)","\tat io.airbyte.persistence.job.DefaultJobPersistence.getJob(DefaultJobPersistence.java:866)","\tat io.airbyte.persistence.job.DefaultJobPersistence.lambda$getJob$32(DefaultJobPersistence.java:862)","\tat io.airbyte.db.Database.query(Database.java:23)","\tat io.airbyte.db.ExceptionWrappingDatabase.query(ExceptionWrappingDatabase.java:31)","\tat io.airbyte.persistence.job.DefaultJobPersistence.getJob(DefaultJobPersistence.java:862)","\tat io.airbyte.commons.server.handlers.JobHistoryHandler.getJobInfo(JobHistoryHandler.java:359)","\tat io.airbyte.server.apis.JobsApiController.lambda$getJobInfo$6(JobsApiController.java:131)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28)","\tat io.airbyte.server.apis.JobsApiController.getJobInfo(JobsApiController.java:131)","\tat io.airbyte.server.apis.$JobsApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)","\tat io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)","\tat io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)","\tat io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465)","\tat io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)","\tat io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1583)","Caused by: org.postgresql.util.PSQLException: This connection has been closed.","\tat org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:1009)","\tat org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1726)","\tat com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:562)","\tat com.zaxxer.hikari.pool.PoolBase.isConnectionDead(PoolBase.java:169)","\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:168)","\t... 29 more"]}
[2024-12-28T17:10:24.220+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 197, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://host.docker.internal:8001/api/v1/jobs/get

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 83, in poke
    job = hook.get_job(job_id=self.airbyte_job_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 161, in get_job
    return self.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 187, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 238, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 201, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 500:Internal Server Error
[2024-12-28T17:10:25.796+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20241228T170323, start_date=20241228T170359, end_date=20241228T171025
[2024-12-28T17:10:27.243+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task airbyte_check_sync (500:Internal Server Error; 390)
[2024-12-28T17:10:28.017+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-28T17:10:29.051+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
