[2024-12-28T13:39:45.470+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T13:39:16.799710+00:00 [queued]>
[2024-12-28T13:39:45.506+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T13:39:16.799710+00:00 [queued]>
[2024-12-28T13:39:45.507+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-28T13:39:45.555+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-12-28 13:39:16.799710+00:00
[2024-12-28T13:39:45.576+0000] {standard_task_runner.py:60} INFO - Started process 524 to run task
[2024-12-28T13:39:45.607+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'manual__2024-12-28T13:39:16.799710+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmp2ey3y6n8']
[2024-12-28T13:39:45.616+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask airbyte_check_sync
[2024-12-28T13:39:46.159+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T13:39:16.799710+00:00 [running]> on host a68ea757822e
[2024-12-28T13:39:46.916+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T13:39:16.799710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T13:39:16.799710+00:00'
[2024-12-28T13:39:47.000+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:39:47.116+0000] {airbyte.py:104} INFO - Waiting for job 53 to complete.
[2024-12-28T13:40:48.223+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:40:48.791+0000] {airbyte.py:104} INFO - Waiting for job 53 to complete.
[2024-12-28T13:41:49.547+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:41:50.188+0000] {airbyte.py:104} INFO - Waiting for job 53 to complete.
[2024-12-28T13:42:55.479+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:42:58.995+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 97, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job was cancelled: 
<Response [200]>
[2024-12-28T13:42:59.202+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20241228T133916, start_date=20241228T133945, end_date=20241228T134259
[2024-12-28T13:42:59.955+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 72 for task airbyte_check_sync (Job was cancelled: 
<Response [200]>; 524)
[2024-12-28T13:43:00.316+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-28T13:43:01.631+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
