[2025-01-06T09:51:02.355+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2025-01-06T09:50:23.104756+00:00 [queued]>
[2025-01-06T09:51:02.371+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2025-01-06T09:50:23.104756+00:00 [queued]>
[2025-01-06T09:51:02.372+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-01-06T09:51:02.404+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2025-01-06 09:50:23.104756+00:00
[2025-01-06T09:51:02.423+0000] {standard_task_runner.py:60} INFO - Started process 338 to run task
[2025-01-06T09:51:02.431+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'manual__2025-01-06T09:50:23.104756+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmp0fszxjln']
[2025-01-06T09:51:02.436+0000] {standard_task_runner.py:88} INFO - Job 136: Subtask airbyte_check_sync
[2025-01-06T09:51:02.541+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2025-01-06T09:50:23.104756+00:00 [running]> on host a68ea757822e
[2025-01-06T09:51:02.739+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T09:50:23.104756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T09:50:23.104756+00:00'
[2025-01-06T09:51:02.769+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2025-01-06T09:51:02.854+0000] {airbyte.py:104} INFO - Waiting for job 71 to complete.
[2025-01-06T09:52:03.385+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2025-01-06T09:52:04.155+0000] {airbyte.py:104} INFO - Waiting for job 71 to complete.
[2025-01-06T09:53:04.228+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2025-01-06T09:53:04.442+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 91, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2025-01-06T09:53:04.517+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20250106T095023, start_date=20250106T095102, end_date=20250106T095304
[2025-01-06T09:53:04.726+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 136 for task airbyte_check_sync (Job failed: 
<Response [200]>; 338)
[2025-01-06T09:53:04.841+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-06T09:53:05.327+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
