[2024-12-28T13:27:21.135+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T13:26:44.745202+00:00 [queued]>
[2024-12-28T13:27:21.152+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T13:26:44.745202+00:00 [queued]>
[2024-12-28T13:27:21.161+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-28T13:27:21.187+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-12-28 13:26:44.745202+00:00
[2024-12-28T13:27:21.201+0000] {standard_task_runner.py:60} INFO - Started process 359 to run task
[2024-12-28T13:27:21.210+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'manual__2024-12-28T13:26:44.745202+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmp_5_af0u0']
[2024-12-28T13:27:21.219+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask airbyte_check_sync
[2024-12-28T13:27:21.339+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T13:26:44.745202+00:00 [running]> on host a68ea757822e
[2024-12-28T13:27:21.739+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T13:26:44.745202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T13:26:44.745202+00:00'
[2024-12-28T13:27:21.805+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:27:21.998+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:28:22.047+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:28:22.079+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:29:22.155+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:29:22.183+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:30:22.285+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:30:22.551+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:31:22.656+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:31:22.688+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:32:22.760+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:32:22.788+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:33:23.674+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:33:24.015+0000] {airbyte.py:104} INFO - Waiting for job 52 to complete.
[2024-12-28T13:34:24.100+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T13:34:24.355+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 91, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2024-12-28T13:34:24.439+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20241228T132644, start_date=20241228T132721, end_date=20241228T133424
[2024-12-28T13:34:25.036+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task airbyte_check_sync (Job failed: 
<Response [200]>; 359)
[2024-12-28T13:34:25.135+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-28T13:34:25.564+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
