[2025-01-07T08:57:38.999+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: postgres_jaffle_to_snowflake.airbyte_trigger_sync scheduled__2025-01-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
