[2024-12-28T15:38:44.009+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T15:37:55.832211+00:00 [queued]>
[2024-12-28T15:38:44.117+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T15:37:55.832211+00:00 [queued]>
[2024-12-28T15:38:44.120+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-28T15:38:44.252+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-12-28 15:37:55.832211+00:00
[2024-12-28T15:38:44.315+0000] {standard_task_runner.py:60} INFO - Started process 1947 to run task
[2024-12-28T15:38:44.341+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'manual__2024-12-28T15:37:55.832211+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmp8h2riy9n']
[2024-12-28T15:38:44.360+0000] {standard_task_runner.py:88} INFO - Job 79: Subtask airbyte_check_sync
[2024-12-28T15:38:44.683+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2024-12-28T15:37:55.832211+00:00 [running]> on host a68ea757822e
[2024-12-28T15:38:45.449+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T15:37:55.832211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T15:37:55.832211+00:00'
[2024-12-28T15:38:45.565+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-28T15:38:45.599+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 83, in poke
    job = hook.get_job(job_id=self.airbyte_job_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 161, in get_job
    return self.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 185, in run
    prepped_request = session.prepare_request(req)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AirbyteTriggerSyncOperator is not JSON serializable
[2024-12-28T15:39:13.474+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20241228T153755, start_date=20241228T153844, end_date=20241228T153913
[2024-12-28T15:39:13.592+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 79 for task airbyte_check_sync (Object of type AirbyteTriggerSyncOperator is not JSON serializable; 1947)
[2024-12-28T15:39:14.131+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-28T15:39:14.349+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
