[2024-12-28T13:44:03.857+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: postgres_jaffle_to_snowflake.airbyte_trigger_sync manual__2024-12-28T13:43:08.695744+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
