[2025-01-06T09:58:51.328+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2025-01-06T09:58:20.015661+00:00 [queued]>
[2025-01-06T09:58:51.362+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2025-01-06T09:58:20.015661+00:00 [queued]>
[2025-01-06T09:58:51.363+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-01-06T09:58:51.423+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2025-01-06 09:58:20.015661+00:00
[2025-01-06T09:58:51.443+0000] {standard_task_runner.py:60} INFO - Started process 443 to run task
[2025-01-06T09:58:51.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'manual__2025-01-06T09:58:20.015661+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmpg20fjmh6']
[2025-01-06T09:58:51.459+0000] {standard_task_runner.py:88} INFO - Job 140: Subtask airbyte_check_sync
[2025-01-06T09:58:51.625+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync manual__2025-01-06T09:58:20.015661+00:00 [running]> on host a68ea757822e
[2025-01-06T09:58:51.950+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T09:58:20.015661+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T09:58:20.015661+00:00'
[2025-01-06T09:58:51.989+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2025-01-06T09:58:52.096+0000] {airbyte.py:104} INFO - Waiting for job 73 to complete.
[2025-01-06T09:59:53.047+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2025-01-06T09:59:53.698+0000] {airbyte.py:104} INFO - Waiting for job 73 to complete.
[2025-01-06T10:00:54.077+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2025-01-06T10:00:54.613+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 91, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2025-01-06T10:00:54.714+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20250106T095820, start_date=20250106T095851, end_date=20250106T100054
[2025-01-06T10:00:55.087+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 140 for task airbyte_check_sync (Job failed: 
<Response [200]>; 443)
[2025-01-06T10:00:55.248+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-06T10:00:55.804+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
